title: NeuroAI and Geometry
url: "https://sychunglab.org/"
markdown: kramdown

nav:
  - name: "Research"
    link: "research" 
  - name: "Highlights"
    link: "highlights"
  - name: "News"
    link: "news"
  - name: "People"
    link: "people" 
  - name: "Publications"
    link: "publications"
  - name: "Talks"
    link: "talks"
  - name: "Contact"
    link: "contact"
