title: NeuroAI and Geometry
url: "http://www.ngayulo.com/"
baseurl: 
markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Highlights"
    link: "highlights"
  - name: "News"
    link: "news"
  - name: "People"
    link: "people" 
  - name: "Publications"
    link: "publications"
  - name: "Talks"
    link: "talks"
  - name: "Contact"
    link: "contact"
